services:
  - type: web
    name: lfbackend
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: APP_SECRET
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
